services:
  backend:
    container_name: backend
    build:
      context: ./Docker/BackEnd # Can fail, replace srcs by correct path *
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "3000:3001" # Access API BackEnd
    restart: unless-stopped
    networks:
      - ft_transcendence
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3001/health || exit 1"]
      timeout: 30s
      retries: 10

  database:
    container_name: database
    image: postgres:latest
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - ft_transcendence
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 30s
      retries: 10

  frontend:
    container_name: frontend
    build:
      context: ./Docker/FrontEnd # --- *
    depends_on:
      backend:
        condition: service_healthy
      database:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "3000:3002"
    restart: unless-stopped
    networks:
      - ft_transcendence

volumes:
  postgres:
    driver: local

networks:
  ft_transcendence:
    name: ft_transcendence
    driver: bridge

