services:
  backend:
    container_name: backend
    build:
      context: ./Docker/BackEnd # Can fail, replace srcs by correct path *
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "3000:3001" # Access API BackEnd
    restart: unless-stopped
    networks:
      - ft_transcendence
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 2s
      timeout: 30s
      retries: 10

  database:
    container_name: database
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped
    networks:
      - ft_transcendence
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"] # don't work for now
      interval: 2s
      timeout: 30s
      retries: 10

  frontend:
    container_name: frontend
    build:
      context: ./Docker/FrontEnd # --- *
    depends_on:
      backend:
        condition: service_healthy
      database:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "3000:3002"
    restart: unless-stopped
    networks:
      - ft_transcendence

volumes:
  postgres_data:
    driver: local

networks:
  ft_transcendence:
    name: ft_transcendence
    driver: bridge

