services:
  backend:
    container_name: backend
    build:
      context: ./srcs/BackEnd # Can fail, replace srcs by correct path *
    depends_on:
      - database
    env_file:
      - .env
    ports:
      - "3001:3001" # Access API BackEnd
    restart: unless-stopped
    networks:
      - ft_transcendence

  database:
    container_name: database
    image: postgres:latest
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - ft_transcendence

  frontend:
    container_name: frontend
    build:
      context: ./srcs/FrontEnd # --- *
    depends_on:
      - backend
      - database
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - ft_transcendence

volumes:
  postgres:
    driver: local

networks:
  ft_transcendence:
    driver: bridge

