FROM vault:1.12.7

RUN apk update && apk add --no-cache curl jq

faire en https dans un autre dossier le certificat ssl
faire un script  pour recupere les secret et les injecter dans les variables d'environnement
une fais les secrets injecter dans les variables d'environnement on peut lancer le serveur django
faire un script pour lancer le serveur django en mode production et dans le front end on peut recuperer les variables d'environnement
rules django
rules vuejs

dabord vault depend de vault init 